### ISSUE TITLE
bug: Invalid hook event types (WorktreeCreateFailed, WorktreeRemoveFailed) crash CC sessions

### ISSUE THREAD

**Issue by OneStepAt4time** [OneStepAt4time/aegis#1002]
## Summary

CC sessions launched via Aegis crash immediately during the thinking phase ("Churning/Incubating/Schlepping → exit"). The root cause is two invalid hook event types in the generated settings file that CC 2.1.91 rejects, causing the **entire settings file to be skipped** — including env vars, auth tokens, and model configuration.

## Root Cause

`hook-settings.ts` line 103-105 includes two event types that do not exist in CC's hook schema:

```typescript
// hook-settings.ts HTTP_HOOK_EVENTS array
'WorktreeCreateFailed',   // ❌ Does not exist in CC
'WorktreeRemoveFailed',   // ❌ Does not exist in CC
```

These were introduced in PR #964 ("feat: register 6 additional CC hook event types #753"), also reflected in `hooks.ts` `KNOWN_HOOK_EVENTS` (lines 59, 61).

## CC Error (visible in terminal)

```
Settings Error:
/tmp/aegis-hooks-1250aff0/hooks-0b2565a7-6a4b-40e4-9bdc-6fb34a437edd.json
└ hooks
  ├ WorktreeCreateFailed: Invalid key in record
  └ WorktreeRemoveFailed: Invalid key in record

Files with errors are skipped entirely, not just the invalid settings.
```

**Critical behavior:** CC does not skip just the invalid keys — it skips the **entire file**. This means all env vars (ANTHROPIC_AUTH_TOKEN, ANTHROPIC_BASE_URL, model overrides), permissions, and valid hooks are also lost.

### CC Official Documentation (code.claude.com/docs/en/hooks)

Supported worktree events:
- `WorktreeCreate` ✅
- `WorktreeRemove` ✅
- `WorktreeCreateFailed` ❌ **Not listed**
- `WorktreeRemoveFailed` ❌ **Not listed**

Full official event list (26 events): SessionStart, UserPromptSubmit, PreToolUse, PermissionRequest, PermissionDenied, PostToolUse, PostToolUseFailure, Notification, SubagentStart, SubagentStop, TaskCreated, TaskCompleted, Stop, StopFailure, TeammateIdle, InstructionsLoaded, ConfigChange, CwdChanged, FileChanged, WorktreeCreate, WorktreeRemove, PreCompact, PostCompact, Elicitation, ElicitationResult, SessionEnd.

### Reproduction

1. Start Aegis server
2. Create a session: `POST /v1/sessions` with any workDir
3. CC boots, shows settings error, crashes during first thinking phase
4. Session shows "Resume this session with: claude --resume ..."

### Verification that CC works without Aegis hooks

```bash
# Manual launch with same settings file but without Aegis hook injection = WORKS
cd /home/bubuntu/projects/aegis
claude --session-id $(uuidgen) --permission-mode bypassPermissions --settings .claude/settings.local.json
# ✅ CC boots and works normally

# Print mode (no settings file involved) = WORKS
claude -p "Say hello" --permission-mode bypassPermissions
# ✅ Responds correctly
```

## Impact

- **P0/Blocker:** ALL Aegis-orchestrated sessions crash on boot
- No sessions can be created via Aegis API
- Affects v2.9.0+ (since PR #964 was merged)
- Manually launched CC sessions are unaffected

### hook-settings.ts
Remove the two invalid event types from `HTTP_HOOK_EVENTS`:
```diff
- 'WorktreeCreateFailed',
- 'WorktreeRemoveFailed',
```

Add missing officially supported events:
```diff
+ 'TaskCreated',
+ 'ConfigChange',
+ 'InstructionsLoaded',
+ 'PermissionDenied',
```

### hooks.ts
Remove from `KNOWN_HOOK_EVENTS`:
```diff
- 'WorktreeCreateFailed',
- 'WorktreeRemoveFailed',
```

Add missing events:
```diff
+ 'TaskCreated',
+ 'ConfigChange',
+ 'InstructionsLoaded',
+ 'PermissionDenied',
```

Remove the handler cases in `processHookEvent()` for the invalid types (lines 91-93, 266-273).

## Regression Source

Introduced by PR #964 (merged 2026-04-03), which added hook event types without verifying them against CC's official schema. The "\*Failed" variants were assumed to exist based on the "\*Create"/"\*Remove" pattern but CC does not implement them.

Related: #753

## Prevention

Add a CI check or test that validates `HTTP_HOOK_EVENTS` against CC's documented hook schema, or at minimum add a comment noting the source of truth (code.claude.com/docs/en/hooks).

## Environment

- CC version: 2.1.91
- Aegis version: 2.10.1
- Node: 22
- OS: Ubuntu 24.04
